const restaurantsTypes={
    ADD_NEW_RESTAURANTS_START:'ADD_NEW_RESTAURANTS_START',
    FETCH_RESTAURANTS_START:'FETCH_RESTAURANTS_START',
    SET_RESTAURANTS:'SET_RESTAURANTS',
    DELETE_RESTAURANTS_START:'DELETE_RESTAURANTS_START'
}

export default restaurantsTypes;